version: '3.8'
services:
  ### Posgres database for Clients
  db-client:
    container_name: db-client
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_client
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    expose:
      - 5432

  ## MySQL database for Accounts
  db-account:
    container_name: db-account
    image: mysql:9.0.1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_account
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306