version: "3.8"
services:
  ### Posgres database for Clients
  db-client:
    container_name: db-client
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_client
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    networks:
      - db-client

  ## MySQL database for Accounts
  db-account:
    container_name: db-account
    image: mysql:9.0.1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_account
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - db-account

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka

  client-ms:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client-ms
    environment:
      - SPRING_DATASOURCE_HOST=db-client
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_GROUP_ID=client-ms
      - PORT=8080
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_USERNAME=test
      - SPRING_FLYWAY_PASSWORD=test
      - SPRING_FLYWAY_HOST=db-client
      - SPRING_FLYWAY_PORT=5432
      - SPRING_FLYWAY_DB=ms_client
      - SPRING_FLYWAY_SCHEMA=public
    depends_on:
      - db-client
      - kafka
    ports:
      - 8080:8080
    networks:
      - db-client
      - kafka

  account-ms:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-ms
    environment:
      - SPRING_DATASOURCE_HOST=db-account
      - SPRING_DATASOURCE_PORT=3306
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_GROUP_ID=account-ms
      - PORT=8081
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_USERNAME=test
      - SPRING_FLYWAY_PASSWORD=test
      - SPRING_FLYWAY_HOST=db-account
      - SPRING_FLYWAY_PORT=3306
      - SPRING_FLYWAY_DB=ms_account
      - SPRING_FLYWAY_SCHEMA=ms_account
    depends_on:
      - db-account
      - kafka
    ports:
      - 8081:8081
    networks:
      - db-account
      - kafka

networks:
  db-account:
    driver: bridge
  db-client:
    driver: bridge
  kafka:
    driver: bridge
  